name: Build Android AAB

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build-aab:
    runs-on: ubuntu-latest
    env:
      ANDROID_KEYSTORE_B64: ${{ secrets.ANDROID_KEYSTORE_B64 }}
      ANDROID_KEYSTORE_PASSWORD: ${{ secrets.ANDROID_KEYSTORE_PASSWORD }}
      ANDROID_KEY_ALIAS: ${{ secrets.ANDROID_KEY_ALIAS }}
      ANDROID_KEY_PASSWORD: ${{ secrets.ANDROID_KEY_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install helpers
        run: |
          sudo apt-get update
          sudo apt-get install -y gettext-base

      - name: Restore keystore from secret
        run: |
          echo "$ANDROID_KEYSTORE_B64" | base64 -d > release.keystore
          ls -l release.keystore

      - name: Render buildozer.spec from template
        run: |
          if [ -f buildozer.spec.template ]; then
            envsubst < buildozer.spec.template > buildozer.spec
          fi
          sed -n '1,120p' buildozer.spec

      - name: Build with Buildozer (Docker image)
        run: |
          docker run --rm -v "$PWD":/home/user/app -w /home/user/app \
            kivy/buildozer \
            buildozer -v android release
        timeout-minutes: 120

      - name: Upload AAB artifact
        uses: actions/upload-artifact@v4
        with:
          name: aab
          path: bin/*.aab
